github: ['mugomes']
custom: ['https://apoia.se/profmu', 'https://www.asaas.com/c/girp15xsowg4dpvf', 'https://www.asaas.com/c/0f9eydhmgg8e3mrj', 'https://donate.stripe.com/14kdSugShfxs9by6oo', 'https://mugomes.github.io/apoie.html']